---
title: "Data Quality Report"
author: "Scott Kreider"
output:
  html_document:
    self_contained: true
    keep_md: true
    toc: true
    toc_float:
      collapsed: false
    toc_depth: 2
sansfont: Calibri Light
params:
  checkDataset: NULL
---

# Runner Summary

```{r echo = FALSE, results = "asis"}
cat(paste0("**Registry:** ",params$checkDataset$runnerSummary$registry,"  \n"))
cat(paste0("**Timestamp:** ",params$checkDataset$runnerSummary$timestamp,"  \n"))
cat(paste0("**User:** ",params$checkDataset$runnerSummary$user,"  \n"))
cat(paste0("**Output location:** ",params$checkDataset$runnerSummary$folderLoc,"  \n"))
cat(paste0("**Data pull date:** ",params$checkDataset$runnerSummary$pullDate,"  \n"))
```

# Overall Check Summary

Critical Check Summary
```{r echo = FALSE, results = "asis"}
summaryToPrint <- params$checkDataset$checkSummary$criticalCheckSummary
DT::datatable(summaryToPrint)

cat(paste0("  \n\n"))
```

Noncritical Check Summary
```{r echo = FALSE, results = "asis"}
DT::datatable(params$checkDataset$checkSummary$nonCriticalCheckSummary)

cat(paste0("  \n\n"))

```


```{r echo = FALSE, results = "asis", include = TRUE}
library(registrydqchecksreportdown)

datasetNames <- names(params$checkDataset$criticalChecks)
for(datasetName in datasetNames){
cat(paste0("  \n\n"))
cat(paste0("# ", datasetName, "  \n\n"))

  cat(paste0("## Summary", "  \n\n"))
  cat(paste0("  \n\n"))
  
  .summaryToPrint <- params$checkDataset$checkSummary$criticalCheckSummary |>
    dplyr::filter(dataset == datasetName)
  print(knitr::kable(.summaryToPrint))

  cat(paste0("  \n\n"))
  
  .summaryToPrint <- params$checkDataset$checkSummary$nonCriticalCheckSummary |>
    dplyr::filter(dataset == datasetName)
  print(knitr::kable(.summaryToPrint))

  cat(paste0("  \n\n"))
  cat(paste0("******  \n"))

  cat(paste0("## Critical Checks", "  \n\n"))
    printCriticalChecks(params$checkDataset$criticalChecks[[datasetName]])

  cat(paste0("******  \n"))
    
  cat(paste0("## Non-Critical Checks", "  \n\n"))
        cat("\n")
      for(.noncriticalCheckId in names(params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks)){
        cat(paste0("******  \n"))
        
        cat("\n")
    
        cat(paste0("###  "
                   ,.noncriticalCheckId
                   ," - ", params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$checkTitle
                   , "  \n"))
        cat(paste0("Description: "
                   ,params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$checkDescription
                   ,"  \n"))
        cat(paste0("Pass: "
                   ,params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$pass
                   ,"  \n"))
        cat(paste0("Number Failed: "
                   ,params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$values$n
                   ,"  \n"))
        cat("\n")

        if(!(params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$values$n %in% c(0, NULL))){
          print(knitr::kable(head(params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$listing)))
          
          if(params$checkDataset$nonCriticalChecks[[datasetName]]$codebookChecks[[.noncriticalCheckId]]$values$n > 6){
            cat(paste0("      *More than 6 observations - see listing output for full list of observations*  \n"))
          }
        }

        cat("\n")
      }

        
        
        
      cat("\n")
      for(.noncriticalCheckId in names(params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList)){
        cat(paste0("******  \n"))
        
        cat("\n")
    
        cat(paste0("###  "
                   ,.noncriticalCheckId
                   ," - ", params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$checkTitle
                   , "  \n"))
        cat(paste0("Description: "
                   ,params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$checkDescription
                   ,"  \n"))
        cat(paste0("Pass: "
                   ,params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$pass
                   ,"  \n"))
        cat(paste0("Number Failed: "
                   ,params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$values$n
                   ,"  \n"))
        cat("\n")
    
        if(params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$values$n > 0){
          print(knitr::kable(head(params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$listing)))
        }

        if(params$checkDataset$nonCriticalChecks[[datasetName]]$nPctList[[.noncriticalCheckId]]$values$n > 6){
          cat(paste0("      *More than 6 observations - see listing output for full list of observations*  \n"))
        }
        cat("\n")
      }
}
```
